#!/bin/bash

# Sets the make.profile symlink.

source /etc/tinderbox.conf

[ -z "$1" ] && echo "Usage: $0 target" && exit 1

portdir=$(portageq get_repo_path / gentoo)
target="$AVAILDIR"/"$1"

rm -f "$target"/etc/portage/make.profile
ln -s "$portdir"/profiles/default/linux/amd64/13.0/no-multilib "$target"/etc/portage/make.profile

