#!/bin/bash

# Detects identical targets in $AVAILDIR and symlinks the unique ones into
# $TARGETSDIR.

source /etc/tinderbox.conf

# All targets
cd "$AVAILDIR"
targets=(*)
cd ->/dev/null

# Targets for symlinking
enabletargets=("${targets[0]}")

for target in "${targets[@]}"; do
	maybeunique=false
	for cmptarget in "${enabletargets[@]}"; do
		diff -r "$AVAILDIR"/"$target" "$AVAILDIR"/"$cmptarget">/dev/null
		# This target is identical to another one, skip it.
		[ $? == 0 ] && continue 2
		# This target isn't indentical to any target tried yet.
		# Mark it as possibly unique and keep comparing.
		maybeunique=true
	done
	# This target is unique
	[ $maybeunique == true ] && enabletargets+=("$target")
done

rm -f "$TARGETSDIR"/*
for target in "${enabletargets[@]}"; do
	ln -s "$AVAILDIR"/"$target" "$TARGETSDIR"
	mkdir -p "$ROOTSDIR"/"$target"
done

sort "$WORLDFILE" | uniq - "$WORLDFILE"

