#!/bin/bash

# Memleek Tinderbox target preparator
# Prepares targets by installing some packages to create a base directory
# structure.

# Public domain/CC0 2016-17 Wiktor W Brodlo <wiktor@brodlo.net>

source /etc/tinderbox.conf

cd "$TARGETSDIR"
for target in *; do
	[ ! -z "$(ls -A $ROOTSDIR/$target)" ] && continue

	gcc-config 5.4.0
	[ "$(tbtargetinfo $target cxxabi)" == 4 ] && gcc-config 4.9.4
	source /etc/profile

	tbemerge "$target" --nodep --oneshot baselayout
	tbemerge "$target" --nodep --oneshot app-portage/elt-patches
	tbemerge "$target" --root-deps=rdeps --oneshot virtual/libc
	USE="internal-glib" tbemerge "$target" --buildpkg=n --oneshot dev-util/pkgconfig
	tbemerge "$target" --root-deps=rdeps --oneshot dev-lang/perl
	USE="-gpg -nls" tbemerge "$target" --buildpkg=n --oneshot dev-vcs/git
	tbemerge "$target" --oneshot sys-devel/gettext
	tbemerge "$target" --keep-going @system
done

