#!/bin/bash

# Memleek Tinderbox package publisher
# Copies binpkgs to public directory

# Public domain/CC0 2017-2018 Wiktor Kerr <w@kerr.sh>

source /etc/tinderbox.conf

chmod ga+rX -Rv "$PKGDIR"
rm -f "$PUBPKGDIR"/*/Packages
rm -rf "$PUBPKGDIR"/*
cp -a "$PKGDIR"/* "$PUBPKGDIR"/
cp -a "$DISTDIR" "$PUBPKGDIR"/ 
chmod ga+rX -Rv "$PUBPKGDIR"

