#!/bin/bash

# Memleek Tinderbox package publisher
# Copies binpkgs to public directory

# Public domain/CC0 2017-2018 Wiktor Kerr <w@kerr.sh>

source /etc/tinderbox.conf

chmod ga+rX -Rv "$PKGDIR"
rm -f "$PUBPKGDIR"/*/Packages
rm -rf "$PUBPKGDIR"/*
cp -a "$PKGDIR"/* "$PUBPKGDIR"/
cp -a "$DISTDIR" "$PUBPKGDIR"/ 
chmod ga+rX -Rv "$PUBPKGDIR"

if [ "$COPYREPO" == "yes" ]; then
	rm -rf "$PUBREPODIR".tmp
	mkdir -p "$PUBREPODIR".tmp
	cp -a "$(portageq get_repo_path / gentoo)"/* "$PUBREPODIR".tmp
	rm -rf "$PUBREPODIR"
	mv "$PUBREPODIR".tmp "$PUBREPODIR"
fi
