#!/bin/bash

# Memleek Tinderbox main script
# Just builds everything everywhere

# Public domain/CC0 2016-17 Wiktor W Brodlo <wiktor@brodlo.net>

source /etc/tinderbox.conf

cd "$TARGETSDIR"
while true; do
	if [ "$SYNCREPOS" == "yes" ]; then
		emerge --sync
		layman -S
	fi

	cd "$REXDIR"
	git pull
	cd -

	tblinktargets
	tbprepare

	gcc-config 5.4.0
	source /etc/profile
	for target in *; do
		targetcxxabi=$(tbtargetinfo "$target" cxxabi)
		[ "$targetcxxabi" == "4" ] && continue
		tbemerge "$target" "@system"
		for pkg in $(cat "$WORLDFILE"); do
			tbemerge "$target" "$pkg"
		done
	done

	gcc-config 4.9.4
	source /etc/profile
	for target in *; do
		targetcxxabi=$(tbtargetinfo "$target" cxxabi)
		[ "$targetcxxabi" == "5" ] && continue
		tbemerge "$target" "@system"
		for pkg in $(cat "$WORLDFILE"); do
			tbemerge "$target" "$pkg"
		done
	done

	chmod ga+rX -Rv "$PKGDIR"
	rm -f "$PUBPKGDIR"/*/Packages
	rm -rf "$PUBPKGDIR"/*
	cp -a "$PKGDIR"/* "$PUBPKGDIR"/
	chmod ga+rX -Rv "$PUBPKGDIR"
done

