#!/bin/bash

# Memleek Tinderbox main script
# Just builds everything everywhere

# Public domain/CC0 2016-17 Wiktor W Brodlo <wiktor@brodlo.net>

source /etc/tinderbox.conf

cd "$TARGETSDIR"
while true; do
	if [ "$SYNCREPOS" == "yes" ]; then
		emerge --sync
		layman -S
	fi

	cd "$REXDIR"
	git pull
	cd -

	tblinktargets
	tbprepare

	for target in *; do
		# Avoid building packages for the wrong C++11 ABI
		targetcxxabi=$(tbtargetinfo "$target" cxxabi)
		hostcxxabi=$(tbtargetinfo / cxxabi)
		[ "$targetcxxabi" != "$hostcxxabi" ] && continue

		tbemerge "$target" "@system"
		for pkg in $(cat "$WORLDFILE"); do
			tbemerge "$target" "$pkg"
		done
	done

	chmod ga+rX -Rv "$PKGDIR"
	rm -f "$PUBPKGDIR"/*/Packages
	rm -rf "$PUBPKGDIR"/*
	cp -a "$PKGDIR"/* "$PUBPKGDIR"/
	chmod ga+rX -Rv "$PUBPKGDIR"
done

