#!/bin/bash

# Memleek Tinderbox main script
# Just builds everything everywhere

# Public domain/CC0 2016-17 Wiktor W Brodlo <wiktor@brodlo.net>

source /etc/tinderbox.conf

cd "$TARGETSDIR"
while true; do
	if [ "$SYNCREPOS" == "yes" ]; then
		emerge --sync
		layman -S
	fi

	if [ "$CLEANAVAILDIR" == "yes" ]; then
		rm -rf "$AVAILDIR"/*
	fi

	sh -c "$UPDATETARGETSCMD"

	tblinktargets
	tbprepare

	for target in *; do
		tbemerge "$target" "@system"
		for pkg in $(cat "$WORLDFILE"); do
			tbemerge "$target" "$pkg"
			# Also package build deps for local rebuilds
			tbemerge "$target" --root-deps "$pkg"
		done
		tbemerge "$target" "@world"
	done

	tbpublish
done

