#!/bin/bash

# Memleek Tinderbox target information tool
# Detects various things about a given target
 
# Public domain/CC0 2016-17 Wiktor W Brodlo <wiktor@brodlo.net>

source /etc/tinderbox.conf

configroot() {
	[ "$1" == '/' ] && echo "" && return 0
	echo --config-root="$AVAILDIR"/"$1"
}

getchost() {
	chost=$(emerge --info $(configroot "$1") 2>/dev/null|fgrep CHOST)
	chost=${chost#CHOST=\"}
	chost=${chost%\"}
	echo "$chost"
}

getcxxabi() {
	portdir=$(portageq get_repo_path / gentoo)
	gcc=$(PORTDIR="$portdir" FEATURES="-getbinpkg" \
		emerge $(configroot "$1") --nodep -pq sys-devel/gcc)
	gcc=${gcc#*gcc-}
	gcc=${gcc%%.*}
	[ "$gcc" -ge 5 ] && gcc=5
	echo "$gcc"
}

getmarch() {
	cflags=$(emerge --info $(configroot "$1") 2>/dev/null|grep ^CFLAGS)
	[[ ! "$cflags" =~ .*march.* ]] && echo "generic" && return 0
	march=${cflags#*march=}
	march=${march%\"}
	echo "$march"
}

[ $# -lt 2 ] && echo "Usage: $0 <target> <info> [...]
where target is a directory under
$AVAILDIR
and info is one or more of chost cxxabi march" && exit 1

target="$1"
shift

while [ ! -z "$1" ]; do
	info="$1"
	shift
	case "$info" in
		"chost" )
			getchost "$target"
			;;
		"cxxabi" )
			getcxxabi "$target"
			;;
		"march" )
			getmarch "$target"
	esac
done

